# Generated by Django 5.2.7 on 2025-10-15 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('check_type', models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField()),
                ('type', models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=16)),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], default='new', max_length=16)),
                ('pdf_file', models.FileField(blank=True, upload_to='pdf')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printer')),
            ],
            options={
                'indexes': [models.Index(models.F('order__id'), name='check_order_id')],
            },
        ),
    ]
